"""
Django settings for myserver project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse

# Load environment variables from a .env file if present
from dotenv import load_dotenv
load_dotenv(os.path.join(Path(__file__).resolve().parent.parent, '.env'))

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-duqoi6mg5@fypw3@hy9%0=50sao8t$eti&_mtqt^(o%tf1yq(^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

raw_allowed_hosts = os.getenv('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip() for host in raw_allowed_hosts.replace(' ', ',').split(',') if host.strip()]

# Reasonable defaults for local dev and Railway deployments.
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['.up.railway.app', '.railway.internal', 'localhost', '127.0.0.1']
else:
    for default_host in ('.up.railway.app', '.railway.internal', 'localhost', '127.0.0.1'):
        if default_host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(default_host)



# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webapp',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'webapp/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
# Uses DATABASE_URL if provided (e.g., for Neon), otherwise environment variables, or defaults to SQLite.
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
    }
elif os.getenv('DJANGO_DB_ENGINE'):
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DJANGO_DB_ENGINE'),
            'NAME': os.getenv('DJANGO_DB_NAME'),
            'USER': os.getenv('DJANGO_DB_USER'),
            'PASSWORD': os.getenv('DJANGO_DB_PASSWORD'),
            'HOST': os.getenv('DJANGO_DB_HOST'),
            'PORT': os.getenv('DJANGO_DB_PORT'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

db_url = os.getenv('DATABASE_URL', '')
if db_url:
    parsed_db_url = urlparse(db_url)
    print(
        f"[startup] DB engine={DATABASES['default'].get('ENGINE')} "
        f"host={parsed_db_url.hostname or ''} "
        f"name={parsed_db_url.path.lstrip('/')}"
    )
else:
    print(
        f"[startup] DB engine={DATABASES['default'].get('ENGINE')} "
        f"host={DATABASES['default'].get('HOST', '')} "
        f"name={DATABASES['default'].get('NAME', '')}"
    )

# Allow the frontend to call APIs
def _parse_origins(value: str):
    origins = []
    for raw_origin in value.split(','):
        origin = raw_origin.strip().rstrip('/')
        if origin:
            origins.append(origin)
    return origins


DEFAULT_FRONTEND_ORIGINS = 'http://localhost:3000,https://studentattendancetrackingsystem.netlify.app'

CORS_ALLOWED_ORIGINS = _parse_origins(
    os.getenv('CORS_ALLOWED_ORIGINS', DEFAULT_FRONTEND_ORIGINS)
)
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = _parse_origins(
    os.getenv('CSRF_TRUSTED_ORIGINS', DEFAULT_FRONTEND_ORIGINS)
)

# Cookie policy:
# - Local HTTP development: Lax + insecure (browser-compatible)
# - Production cross-site (Netlify -> Railway): None + secure
if DEBUG:
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
# settings.py
AUTH_USER_MODEL = 'webapp.User'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True # Use TLS for security
EMAIL_HOST_USER = 'nyikogiven74@gmail.com'  
EMAIL_HOST_PASSWORD = 'rzcksgqksodfuqwl' # Use an App Password if 2FA is enabled

# 

# Media (uploaded images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
