# Generated by Django 5.2.12 on 2026-03-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_faceencoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_code', models.CharField(help_text='Unique code for the module.', max_length=20, primary_key=True, serialize=False)),
                ('module_name', models.CharField(help_text='Human-readable name for the module.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the module.', null=True)),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['module_code'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.ForeignKey(blank=True, help_text='The module this course belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='webapp.module'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='module',
            field=models.ForeignKey(blank=True, help_text="The module the student is enrolled in (should match the course's module).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='webapp.module'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='Modules that this lecturer is assigned to.', related_name='lecturers', to='webapp.module'),
        ),
        migrations.AddField(
            model_name='student',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='Modules that this student is enrolled in.', related_name='students', to='webapp.module'),
        ),
    ]
