# Generated by Django 5.2.12 on 2026-03-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_module_course_module_enrollment_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_code', models.CharField(help_text='Unique code for the program.', max_length=20, primary_key=True, serialize=False)),
                ('program_name', models.CharField(help_text='Human-readable name for the program.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the program.', null=True)),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'ordering': ['program_code'],
            },
        ),
        migrations.AddField(
            model_name='lecturer',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Programs that this lecturer is associated with.', related_name='lecturers', to='webapp.program'),
        ),
        migrations.AddField(
            model_name='student',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Programs that this student is enrolled in.', related_name='students', to='webapp.program'),
        ),
    ]
