# Generated by Django 5.2.12 on 2026-03-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_program_lecturer_programs_student_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='module',
        ),
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='Modules associated with this course (e.g., Year 1, Year 2, etc.).', related_name='courses', to='webapp.module'),
        ),
    ]
