# Generated by Django 5.2.12 on 2026-03-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_course_lecturer_remove_course_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='module',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='The module(s) the student is enrolled in for this course.', related_name='enrollments', to='webapp.module'),
        ),
    ]
