# Generated by Django 5.2.12 on 2026-03-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_enrollment_module_enrollment_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='module',
            field=models.ForeignKey(blank=True, help_text='The specific module covered in this session.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='webapp.module'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course'),
        ),
    ]
